import JSZip from "jszip";
import { NextRequest } from "next/server";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    if (!body || !Array.isArray(body.scenes)) {
      return new Response(
        JSON.stringify({ ok: false, error: "INVALID_PAYLOAD" }),
        { status: 400, headers: { "content-type": "application/json; charset=utf-8" } }
      );
    }

    const zip = new JSZip();

    // project.json
    zip.file("project.json", JSON.stringify(body, null, 2));

    // scene files
    for (let i = 0; i < body.scenes.length; i++) {
      const scene = body.scenes[i] || {};
      const idx = String(i + 1).padStart(2, "0");

      const parts: string[] = [];
      parts.push("SCENE " + idx);
      parts.push("");
      parts.push("NARRATIVE:");
      parts.push(String(scene.narrative ?? "-"));
      parts.push("");
      parts.push("IMAGE PROMPT A:");
      parts.push(String(scene.imagePromptA ?? "-"));
      parts.push("");
      parts.push("IMAGE PROMPT B:");
      parts.push(String(scene.imagePromptB ?? "-"));
      parts.push("");
      parts.push("VIDEO PROMPT:");
      parts.push(String(scene.videoPrompt ?? "-"));
      parts.push("");

      zip.file("scene-" + idx + ".txt", parts.join("\n"));
    }

    // readme
    zip.file(
      "README.txt",
      ["YosoApp Export", "", "Scenes: " + String(body.scenes.length), "Generated by YosoApp Builder", ""].join("\n")
    );

    const arrayBuf = await zip.generateAsync({ type: "arraybuffer" });

    return new Response(arrayBuf, {
      headers: {
        "content-type": "application/zip",
        "content-disposition": "attachment; filename=yoso-project.zip",
        "cache-control": "no-store"
      }
    });
  } catch (e: any) {
    return new Response(
      JSON.stringify({ ok: false, error: e?.message || "EXPORT_FAILED" }),
      { status: 500, headers: { "content-type": "application/json; charset=utf-8" } }
    );
  }
}